#include <string>

std::string f_embeded_GLSL_source_base_glsl()
{
    return "#version 330 core\n"
"\n"
"in vec3 WorldPos;\n"
"in vec3 LocalPos;\n"
"in vec2 TexCoord;\n"
"\n"
"// texture samplers\n"
"uniform sampler2D texture1;\n"
"uniform sampler2D texture2;\n"
"\n"
"out vec4 FragColor;\n"
"uniform vec3 uColor;\n"
"\n"
"uniform float time;\n"
"uniform vec3 uCamPos;        // Camera position in world space\n"
"\n"
"uniform vec3 uCubePos; // Cube position\n"
"\n"
"\n"
"\n"
"\n"
"// global variables\n"
"vec3 camera = vec3(0.0, 0.0, 0.0);\n"
"vec2 uv = vec2(0.0, 0.0);\n"
"float iTime = 0.0;\n"
"vec4 iMouse = vec4(0.0, 0.0, 0.0, 0.0);\n"
"\n"
"void init()\n"
"{\n"
"    iTime = time;\n"
"\n"
"    uv = TexCoord;\n"
"}\n"
"\n"
"\n"
"float f_border(vec2 uv, float border_size)\n"
"{\n"
"    float value = 0;\n"
"    float min_border = border_size;\n"
"    float max_border = 1.0 - border_size;\n"
"    if (\n"
"        uv.x > min_border && uv.x < max_border &&\n"
"        uv.y > min_border && uv.y < max_border\n"
"        )\n"
"    {\n"
"        value = 1.0;\n"
"    }\n"
"    return value;\n"
"}\n"
"\n"
"// Distance to the scene\n"
"// SDF function lib\n"
"\n"
"float sdSphere(vec3 p, float s)\n"
"{\n"
"    return length(p) - s;\n"
"}\n"
"\n"
"float sdBox(vec3 p, vec3 b)\n"
"{\n"
"    vec3 q = abs(p) - b;\n"
"    return length(max(q, 0.0)) + min(max(q.x, max(q.y, q.z)), 0.0);\n"
"}\n"
"\n"
"float smin(float a, float b, float k)\n"
"{\n"
"    float h = max(k - abs(a - b), 0.0) / k;\n"
"    return min(a, b) - h * h * h * k * (1.0 / 6.0);\n"
"}\n"
"\n"
"mat2 rot2D(float angle)\n"
"{\n"
"    float s = sin(angle);\n"
"    float c = cos(angle);\n"
"    return mat2(c, -s, s, c);\n"
"}\n"
"\n"
"vec3 palette(float t)\n"
"{\n"
"    vec3 a = vec3(0.5, 0.5, 0.5);\n"
"    vec3 b = vec3(0.5, 0.5, 0.5);\n"
"    vec3 c = vec3(1.0, 1.0, 1.0);\n"
"    vec3 d = vec3(0.263, 0.416, 0.557);\n"
"\n"
"    return a + b * cos(6.28318 * (c * t + d));\n"
"}\n"
"\n"
"float sdOctahedron(vec3 p, float s)\n"
"{\n"
"    p = abs(p);\n"
"    return (p.x + p.y + p.z - s) * 0.57735027;\n"
"}\n"
"\n"
"vec3 erot(vec3 p, vec3 ax, float ro) {\n"
"    return mix(dot(ax, p) * ax, p, cos(ro)) + cross(ax, p) * sin(ro);\n"
"}\n"
"\n"
"float lighting(vec3 normal, int type)\n"
"{\n"
"    if (type == 0) {\n"
"        //phong diffuse lighting\n"
"        vec3 lightDir = normalize(vec3(1));\n"
"        return max(dot(lightDir, normal), 0.);\n"
"    }\n"
"    if (type == 1) {\n"
"        //hemispherical lighting\n"
"        vec3 lightDir = normalize(vec3(1));\n"
"        return dot(lightDir, normal) * .5 + .5;\n"
"    }\n"
"    if (type == 2) {\n"
"        //\"leaky\" phong diffuse lighting\n"
"        vec3 lightDir = normalize(vec3(1));\n"
"        float shade = dot(lightDir, normal);\n"
"        return mix(max(shade, 0.), shade * .5 + .5, .05);\n"
"    }\n"
"    if (type == 3) {\n"
"        //axis lighting\n"
"        return dot(max(normal, 0.), vec3(.4));\n"
"    }\n"
"    if (type == 4) {\n"
"        //downward pointing axis lighting\n"
"        normal = erot(normal, normalize(vec3(-1, 1, 0)), .96);\n"
"        return dot(max(normal, 0.), vec3(.4));\n"
"    }\n"
"    if (type == 5) {\n"
"        //image based lighting\n"
"        // return pow(textureLod(iChannel0, normal.xzy, 7.).x, 2.);\n"
"        return 1.0;\n"
"    }\n"
"    if (type == 6) {\n"
"        //fake image based lighting (\"studio lighting\")\n"
"        return pow(length(sin(normal * 2.) * .5 + .5) / sqrt(3.), 2.);\n"
"    }\n"
"    if (type == 7) {\n"
"        //fake image based lighting (\"outdoor lighting\")\n"
"        return length(sin(normal * 2.) * .5 + .5) / sqrt(3.) * smoothstep(-1., 1., normal.z);\n"
"    }\n"
"    return 0.;\n"
"}\n"
"\n"
"float sdBoxFrame(vec3 p, vec3 b, float e)\n"
"{\n"
"    p = abs(p) - b;\n"
"    vec3 q = abs(p + e) - e;\n"
"    return min(min(\n"
"        length(max(vec3(p.x, q.y, q.z), 0.0)) + min(max(p.x, max(q.y, q.z)), 0.0),\n"
"        length(max(vec3(q.x, p.y, q.z), 0.0)) + min(max(q.x, max(p.y, q.z)), 0.0)),\n"
"        length(max(vec3(q.x, q.y, p.z), 0.0)) + min(max(q.x, max(q.y, p.z)), 0.0));\n"
"}\n"
"\n"
"float sdRoundBox(vec3 p, vec3 b, float r)\n"
"{\n"
"    vec3 q = abs(p) - b + r;\n"
"    return length(max(q, 0.0)) + min(max(q.x, max(q.y, q.z)), 0.0) - r;\n"
"}\n"
"\n"
"float sdTorus(vec3 p, vec2 t)\n"
"{\n"
"    vec2 q = vec2(length(p.xz) - t.x, p.y);\n"
"    return length(q) - t.y;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"struct Ray\n"
"{\n"
"    int i; // iteration\n"
"    vec3 p; // position\n"
"    vec3 normal;\n"
"    float t; // total distance travelled by ray\n"
"};\n"
"\n"
"float sdf_debug_wireframe(vec3 q)\n"
"{\n"
"    return sdBoxFrame(q, vec3(2.0, 2.0, 2.0), 0.1);\n"
"}\n"
"\n"
"\n"
"\n"
"float sdf_0000(vec3 p)\n"
"{\n"
"\n"
"\n"
"    float box_size = 2.0;\n"
"    float box_x = sdBox(p, vec3(box_size, 0.1, 0.1)); // Cube SDF\n"
"    float box_y = sdBox(p, vec3(0.1, box_size, 0.1)); // Cube SDF\n"
"    float box_z = sdBox(p, vec3(0.1, 0.1, box_size)); // Cube SDF\n"
"\n"
"    vec3 spherePos = vec3(2, 0, 0);\n"
"    float sphere = sdSphere(p - spherePos, 0.42); // Spere SDF \n"
"\n"
"    // vec3 spherePos = vec3(0, 0, 0);\n"
"    // float sphere = sdSphere(q - spherePos, 0.1); // Spere SDF \n"
"    // return smin(box , sphere , 2.0);\n"
"    // return sphere;\n"
"\n"
"    float v = 999999;\n"
"    float v_fak = 1.0;\n"
"    v = smin(v, box_x, v_fak);\n"
"    v = smin(v, box_y, v_fak);\n"
"    v = smin(v, box_z, v_fak);\n"
"\n"
"    // v = smin(v, sphere, 0.42);\n"
"\n"
"    return v;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*\n"
"float sd_0000(vec3 p, float v)\n"
"{\n"
"    loat camera_x = (camera.x + camera.y + camera.z) * 0.02;\n"
"    float positional_variance = sin((uCubePos.x + uCubePos.y + uCubePos.z + camera_x) * 100.0);\n"
"\n"
"    float d_box = sdBox(cube_space - box_position, vec3(0.2 + sin(time * 0.2 + positional_variance) * 0.2f));\n"
"\n"
"    v = smin(v, d_box, 0.1);\n"
"    return v;\n"
"}\n"
"*/\n"
"\n"
"//#REPLACE_FUNCTION_DEFINITIONS\n"
"\n"
"float map(vec3 p)\n"
"{\n"
"\n"
"    // space repetition and id\n"
"    // vec3 s = vec3(4.0, 4.0, 4.0);\n"
"    // vec3 id = round(p / s);\n"
"    // vec3 q = p - s * id;\n"
"\n"
"\n"
"    // sdf\n"
"    float v = 10000000.0;\n"
"\n"
"    vec3 cube_space = p - uCubePos - vec3(0.5);\n"
"\n"
"    vec3 box_position = vec3(0.0, 0.0, 0.0);\n"
"    // return sdBox(cube_space - box_position, vec3(0.497));\n"
"\n"
"    float d_box_frame = sdBoxFrame(cube_space - box_position, vec3(0.497), 0.02);\n"
"\n"
"    v = smin(v, d_box_frame, 0.1);\n"
"\n"
"    //#REPLACE_INSIDE_MAP_FUNCTION\n"
"\n"
"    return v;\n"
"}\n"
"\n"
"\n"
"\n"
"vec3 texture_0000(Ray ray)\n"
"{\n"
"    vec3 color = vec3(0.0, 0.0, 0.0);\n"
"\n"
"    float d0 = dot(vec3(1.0, 0.0, 0.0), ray.normal);\n"
"    float d1 = dot(vec3(0.0, 1.0, 0.0), ray.normal);\n"
"    float d2 = dot(vec3(1.0, 0.0, 1.0), ray.normal);\n"
"\n"
"    float g0 = min(1.0, pow(abs(sin(ray.p.x * 10)) * abs(sin(ray.p.z * 10)), 0.5));\n"
"    float g1 = min(1.0, pow(abs(sin(ray.p.x * 10)) * abs(sin(ray.p.y * 10)), 0.5));\n"
"    float g2 = min(1.0, pow(abs(sin(ray.p.y * 10)) * abs(sin(ray.p.z * 10)), 0.5));\n"
"    // color.r = abs(sin(ray.p.x));\n"
"    // color.g = abs(sin(ray.p.y));\n"
"    // color.b = abs(sin(ray.p.z));\n"
"\n"
"    vec3 v0 = palette(sin((d0 * g0 * d1 * g1 * d2 * g2) * 420.0));\n"
"    vec3 v1 = palette((d0 * g0 + d1 * g1 + d2 * g2) * (1.0 / 3.0));\n"
"    return v1 * (0.75 + 0.25 * v0);\n"
"    // color.r = d0 * g0; // top\n"
"    // color.g = d1 * g1; // front\n"
"    // color.b = d2 * g2; // left\n"
"    // return color;\n"
"    // return vec3(1.0, 1.0, 1.0);\n"
"}\n"
"\n"
"\n"
"\n"
"vec3 texture_0001(Ray ray)\n"
"{\n"
"    vec3 color = vec3(1.0, 1.0, 1.0);\n"
"\n"
"    float d0 = dot(vec3(1.0, 0.0, 0.0), ray.normal);\n"
"    float d1 = dot(vec3(0.0, 1.0, 0.0), ray.normal);\n"
"    float d2 = dot(vec3(0.0, 0.0, 1.0), ray.normal);\n"
"\n"
"    vec4 color_0 = texture(texture1, vec2(ray.p.z * 1.0, ray.p.x * 1.0));\n"
"    vec4 color_1 = texture(texture1, vec2(ray.p.x * 1.0, ray.p.y * 1.0));\n"
"    vec4 color_2 = texture(texture1, vec2(ray.p.y * 1.0, ray.p.z * 1.0));\n"
"\n"
"    // color.r = (color_0.r + color_1.r + color_2.r) * 0.3;\n"
"    // color.g = (color_0.g + color_1.g + color_2.g) * 0.3;\n"
"    // color.b = (color_0.b + color_1.b + color_2.b) * 0.3;\n"
"\n"
"\n"
"\n"
"    d0 = max(min(1.0, abs(d0)), 0.0);\n"
"    d1 = max(min(1.0, abs(d1)), 0.0);\n"
"    d2 = max(min(1.0, abs(d2)), 0.0);\n"
"\n"
"    d0 = pow(d0, 1.0);\n"
"    d1 = pow(d1, 1.0);\n"
"    d2 = pow(d2, 1.0);\n"
"\n"
"    // d1 = 0.0;\n"
"    // d0 = 0.0;\n"
"    // d2 = 0.0;\n"
"\n"
"    color =\n"
"        color_2.xyz * d0 +\n"
"        color_0.xyz * d1 +\n"
"        color_1.xyz * d2;\n"
"\n"
"\n"
"    float factor = 1.0;\n"
"\n"
"    factor = sin(sin(ceil(ray.p.x) * 21.0) + sin(ceil(ray.p.y) * 27.0) + sin(ceil(ray.p.z) * 27.0) + time);\n"
"\n"
"    float factor_r = sin(sin(ceil(ray.p.x) * 41.0) + sin(ceil(ray.p.y) * 77.0) + sin(ceil(ray.p.z) * 47.0) + time * 0.47);\n"
"    float factor_g = sin(sin(ceil(ray.p.x + 10) * 6123.0) + sin(ceil(ray.p.y + 4) * 7127.0) + sin(ceil(ray.p.z) * 47.0) + time * 0.7);\n"
"    float factor_b = sin(sin(ceil(ray.p.x - 2) * 414.0) + sin(ceil(ray.p.y + 2) * 7723.0) + sin(ceil(ray.p.z) * 4477.0) + time * 0.2);\n"
"\n"
"    color *= mix(vec3(1.0, 1.0, 1.0), vec3(factor_r + 0.5, factor_g + 0.5, factor_b + 0.5) * factor, abs(sin(time * 0.2)));\n"
"\n"
"\n"
"    return color;\n"
"}\n"
"\n"
"\n"
"vec3 texture_main(Ray ray)\n"
"{\n"
"    int material = 0;\n"
"\n"
"    // space repetition and id\n"
"    vec3 s = vec3(4.0, 4.0, 4.0);\n"
"    vec3 id = round(ray.p / s);\n"
"    vec3 q = ray.p - s * id;\n"
"\n"
"\n"
"    // return texture_0001(ray);\n"
"    // vec4 color = texture(texture1, uv);\n"
"    // return vec3(color.r, color.g, color.b);\n"
"\n"
"    /*\n"
"    if (mod(id.x, 2) == 0)\n"
"    {\n"
"        material = 1;\n"
"    }\n"
"    else if (mod(id.z, 2) == 0)\n"
"    {\n"
"        material = 2;\n"
"    }\n"
"\n"
"    if (material == 0)\n"
"    {\n"
"        return texture_0000(ray);\n"
"    }\n"
"    else if (material == 1)\n"
"    {\n"
"        return vec3(1.0, 1.0, 1.0);\n"
"    }\n"
"    */\n"
"    // return texture_0000(ray);\n"
"    // return vec3(1.0, 1.0, 1.0);\n"
"\n"
"    return texture_generated(ray);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*\n"
"float map(vec3 p)\n"
"{\n"
"    vec3 repeated_space = vec3(fract(p.x * 1.0) - 0.5, fract(p.y * 1.0) - 0.5, fract(p.z * 1.0) - 0.5);\n"
"    vec3 cube_space = p - uCubePos - vec3(0.5);\n"
"\n"
"    // vec3 sphere_position = vec3(0.1 * sin(time), 0.0, 0.1 * cos(time));\n"
"\n"
"    // float box = sd_box(p - uCubePos - vec3(1.0, 1.0, 1.0), vec3(0.2, 0.2, 0.2));\n"
"\n"
"    // vec3 sphere_position = vec3(0.1 * sin(time), 0.0, 0.1 * cos(time));\n"
"\n"
"    // float distance = 9999.9;\n"
"\n"
"    // return smin(sd_sphere(repeated_space - sphere_position, 0.2), box, 0.1);\n"
"\n"
"    vec3 sphere_position = vec3(0.1 * sin(time), 0.0, 0.1 * cos(time));\n"
"\n"
"    // float distance = sd_sphere(repeated_space - sphere_position, 0.2);\n"
"    float distance = sdSphere(cube_space + sphere_position, 0.2 + 0.01 * sin(p.y * p.z * p.x+ time));\n"
"\n"
"    distance = sdRoundBox(cube_space, vec3(0.5, 0.5, 0.5), 0.1);\n"
"\n"
"    return distance;\n"
"}\n"
"*/\n"
"\n"
"// 4 samples\n"
"\n"
"vec3 calcNormal(in vec3 p) // for function f(p)\n"
"{\n"
"    const float h = 0.0001; // replace by an appropriate value\n"
"    const vec2 k = vec2(1, -1);\n"
"    return normalize(k.xyy * map(p + k.xyy * h) +\n"
"        k.yyx * map(p + k.yyx * h) +\n"
"        k.yxy * map(p + k.yxy * h) +\n"
"        k.xxx * map(p + k.xxx * h));\n"
"}\n"
"\n"
"\n"
"// 6 samples\n"
"/*\n"
"vec3 calcNormal(vec3 p) // for function f(p)\n"
"{\n"
"    const float eps = 0.0001; // or some other value\n"
"    const vec2 h = vec2(eps, 0);\n"
"    return normalize(vec3(map(p + h.xyy) - map(p - h.xyy),\n"
"        map(p + h.yxy) - map(p - h.yxy),\n"
"        map(p + h.yyx) - map(p - h.yyx)));\n"
"}\n"
"*/\n"
"\n"
"float calcOcc(vec3 pos, vec3 nor)\n"
"{\n"
"    const float h = 0.15;\n"
"    float ao = 0.0;\n"
"\n"
"    for (int i = 0; i < 8; i++)\n"
"    {\n"
"        vec3 dir = sin(float(i) * vec3(1.0, 7.13, 13.71) + vec3(0.0, 2.0, 4.0));\n"
"        dir = dir + 2.5 * nor * max(0.0, -dot(nor, dir));\n"
"        float d = map(pos + h * dir);\n"
"        ao += max(0.0, h - d);\n"
"    }\n"
"    return clamp(1.0 - 0.7 * ao, 0.0, 1.0);\n"
"}\n"
"\n"
"float calcSoftshadow(in vec3 ro, in vec3 rd, in float mint, in float tmax, in float w, int technique)\n"
"{\n"
"    float res = 1.0;\n"
"    float t = mint;\n"
"    float ph = 1e10; // big, such that y = 0 on the first iteration\n"
"\n"
"    for (int i = 0; i < 32; i++)\n"
"    {\n"
"        float h = map(ro + rd * t);\n"
"\n"
"        // traditional technique\n"
"        if (technique == 0)\n"
"        {\n"
"            res = min(res, h / (w * t));\n"
"        }\n"
"        // improved technique\n"
"        else\n"
"        {\n"
"            // use this if you are getting artifact on the first iteration, or unroll the\n"
"            // first iteration out of the loop\n"
"            //float y = (i==0) ? 0.0 : h*h/(2.0*ph); \n"
"\n"
"            float y = h * h / (2.0 * ph);\n"
"            float d = sqrt(h * h - y * y);\n"
"            res = min(res, d / (w * max(0.0, t - y)));\n"
"            ph = h;\n"
"        }\n"
"\n"
"        t += h;\n"
"\n"
"        if (res<0.0001 || t>tmax) break;\n"
"\n"
"    }\n"
"    res = clamp(res, 0.0, 1.0);\n"
"    return res * res * (3.0 - 2.0 * res);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"const float max_draw_distance = 100.0;\n"
"const float min_distance = 0.001;\n"
"\n"
"\n"
"\n"
"Ray raymarch(vec3 ro, vec3 rd)\n"
"{\n"
"    Ray ray;\n"
"\n"
"    for (ray.i = 0; ray.i < 200; ray.i++)\n"
"    {\n"
"        ray.p = ro + rd * ray.t; // position along the ray\n"
"\n"
"        float d = map(ray.p); // current distance to the scene\n"
"\n"
"        ray.t += d; // \"march\" the ray\n"
"\n"
"        if (d < min_distance || ray.t > max_draw_distance) break;\n"
"    }\n"
"\n"
"    return ray;\n"
"}\n"
"\n"
"float softshadow(in vec3 ro, in vec3 rd, float mint, float maxt, float w)\n"
"{\n"
"    float res = 1.0;\n"
"    float t = mint;\n"
"    for (int i = 0; i < 256 && t < maxt; i++)\n"
"    {\n"
"        float h = map(ro + t * rd);\n"
"        res = min(res, h / (w * t));\n"
"        t += clamp(h, 0.005, 0.50);\n"
"        if (res<-1.0 || t>maxt) break;\n"
"    }\n"
"    res = max(res, -1.0);\n"
"    return 0.25 * (1.0 + res) * (1.0 + res) * (2.0 - res);\n"
"}\n"
"\n"
"struct Light\n"
"{\n"
"    vec3 position;\n"
"    vec3 color;\n"
"    float brightness;\n"
"};\n"
"\n"
"float hardShadow(vec3 ro, vec3 rd, float maxDist) {\n"
"    float t = 0.01; // Start slightly away from the surface\n"
"    for (int i = 0; i < 10; i++) { // Much fewer steps\n"
"        float h = map(ro + rd * t);\n"
"        if (h < 0.001) return 0.0; // Hit something\n"
"        t += h;\n"
"        if (t > maxDist) break;\n"
"    }\n"
"    return 1.0; // No hit\n"
"}\n"
"\n"
"\n"
"vec3 calculate_lighting(Light light, Ray ray)\n"
"{\n"
"    float angle = abs(1.0 - dot(normalize(light.position - ray.p), normalize(ray.p - camera)));\n"
"    float light_distance = distance(light.position, ray.p);\n"
"    float light_value = (1.0 / (0.01 + pow(light_distance, 2.0))) * light.brightness * angle;\n"
"\n"
"    vec3 light_out = vec3(light_value) * light.color;\n"
"\n"
"    // soft shadows\n"
"    // float factor_shadow = softshadow(ray.p + ray.normal * min_distance * 2.4, normalize(light.position - ray.p), 0.1, 10.0, 0.24);\n"
"    float factor_shadow = hardShadow(ray.p + ray.normal * min_distance * 2.4, normalize(light.position - ray.p), 10.0);\n"
"    light_out *= (0.24 + factor_shadow * 0.76);\n"
"\n"
"    return light_out;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*\n"
"void main()\n"
"{\n"
"    FragColor = vec4(uColor, 1.0);\n"
"\n"
"\n"
"\n"
"    // FragColor = mix(texture(texture1, TexCoord), texture(texture2, TexCoord), 1.0) + abs(sin(time * 0.1 + (uv.x * 100.0 * uv.y * 100.0 + time)));\n"
"    // vec2 uv_0 = vec2(uv.x, uv.y + 0.1 * sin(uv.x * 100.0 + time * 0.2));\n"
"    // vec2 uv_1 = vec2(uv.x, uv.y + 0.1 * sin(uv.y * 100.0 + time * 0.2));\n"
"    // FragColor = mix(texture(texture1, uv_0), texture(texture2, uv_1), abs(sin(time + sin(uv.x * 10.0 - uv.y * 10.0 + time * 0.2))));\n"
"    float r = 0.4;\n"
"    float g = 0.4;\n"
"    float b = 0.4;\n"
"\n"
"    float value = f_border(uv, 0.01 + 0.002 * sin(time + uv.x * 100.0 + uv.y * 100.0));\n"
"\n"
"\n"
"    // FragColor = vec4(r, g, b, 1.0);\n"
"\n"
"    // vec2 uv_offset = vec2(0.0, 0.0 + time * 0.01 + 0.01 * sin(uv.x * 100.0 + uv.y * 20));\n"
"\n"
"    //FragColor = texture(texture1, uv + uv_offset) * value * 1.0;\n"
"\n"
"    vec3 camera_position = uCamPos;\n"
"    camera = camera_position;\n"
"    vec3 world_position = WorldPos;\n"
"    vec3 local_position = LocalPos;\n"
"    vec3 cube_position = uCubePos;\n"
"\n"
"    float dx = camera_position.x - world_position.x;\n"
"    float dy = camera_position.y - world_position.y;\n"
"    float dz = camera_position.z - world_position.z;\n"
"\n"
"    float distance_to_camera = sqrt(dx * dx + dy * dy + dz * dz);\n"
"\n"
"\n"
"\n"
"    float factor = distance_to_camera;\n"
"    factor = factor * 0.07 + 0.2 * sin(distance_to_camera * 10.0 - time);\n"
"\n"
"    // Initilizalization\n"
"    vec3 ro = vec3(camera_position.x, camera_position.y, camera_position.z); // ray origin\n"
"    vec3 rd = normalize(world_position - ro);\n"
"    vec3 col = vec3(0);\n"
"\n"
"    float t = 0.0;\n"
"\n"
"    // Raymarching\n"
"\n"
"    vec3 n;\n"
"\n"
"    for (int i = 0; i < 80; i++)\n"
"    {\n"
"        vec3 p = ro + rd * t; // position along the ray\n"
"\n"
"        float d = map(p); // current distance to the scene\n"
"\n"
"        n = calcNormal(p);\n"
"\n"
"        t += d; // \"march\"the ray\n"
"\n"
"        col = vec3(i) / 80.0;\n"
"\n"
"        col *= dot(rd, n);\n"
"\n"
"        if (d < 0.001 || t > 100.0)\n"
"        {\n"
"            break;\n"
"        }\n"
"\n"
"\n"
"    }\n"
"\n"
"    // col = vec3(t * 0.01);\n"
"\n"
"    // col = vec3(1.0-col.r, 1.0 - col.g, 1.0 - col.b) * vec3(texture(texture1, uv));\n"
"\n"
"\n"
"\n"
"\n"
"    // FragColor = vec4(vec3(rd.x, rd.y, rd.z) * factor, 1.0);\n"
"    FragColor = vec4(col, 1.0);\n"
"\n"
"\n"
"\n"
"}\n"
"*/\n"
"\n"
"void main()\n"
"{\n"
"    // ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);\n"
"\n"
"    init();\n"
"\n"
"    vec3 camera_position = uCamPos;\n"
"    camera = camera_position;\n"
"\n"
"    vec3 world_position = WorldPos;\n"
"\n"
"    // Camera movment\n"
"    // camera += vec3(0.0, 0.0, iTime * 0.42);\n"
"\n"
"    // float fov_factor = 45.0;\n"
"\n"
"    // Initialization\n"
"    vec3 ro = camera; // ray origin\n"
"    // vec3 rd = normalize(vec3(uv * fov_factor, 1.0)); // ray direction\n"
"    vec3 rd = normalize(world_position - ro);\n"
"\n"
"    // Raymarching\n"
"    Ray ray = raymarch(ro, rd);\n"
"    ray.normal = calcNormal(ray.p);\n"
"\n"
"    // non positional lights     \n"
"\n"
"    float light_non_positional = 0.0;\n"
"    light_non_positional += lighting(ray.normal, 6) * 0.5;\n"
"    light_non_positional += lighting(ray.normal, 3) * 0.5;\n"
" // light_non_positional *= calcOcc(ray.p, ray.normal);\n"
"    light_non_positional *= 0.24;\n"
"\n"
"    vec3 light = vec3(0.0, 0.0, 0.0);\n"
"    light += vec3(light_non_positional);\n"
"\n"
"\n"
"    // point light 0\n"
"\n"
"    Light light_0;\n"
"    light_0.position = camera;// vec3(camera.x + 7.0, camera.y + 24.0 * sin(iTime * 0.42), camera.z + 4);\n"
"    light_0.color = vec3(0.7, 1.0, 0.7);\n"
"    light_0.brightness = 0.2 + 0.2 * abs(sin(time * 0.1));\n"
"\n"
"    light += calculate_lighting(light_0, ray);\n"
"\n"
"\n"
"    // point light 1\n"
"\n"
"    Light light_1;\n"
"    light_1.position = vec3(camera.x - 7.0, camera.y + 24.0 * cos(iTime * 0.42), camera.z + 4);\n"
"    light_1.color = vec3(0.7, 0.7, 1.0);\n"
"    light_1.brightness = 42.0;\n"
"\n"
"    light += calculate_lighting(light_1, ray);\n"
"\n"
"\n"
"    // Coloring\n"
"    vec3 col = vec3(1);\n"
"\n"
"    // background\n"
"    if (ray.t > max_draw_distance)\n"
"    {\n"
"        col = vec3(0);\n"
"    }\n"
"\n"
"    col *= texture_main(ray);\n"
"    col *= light;\n"
"\n"
"\n"
"    // color    \n"
"    col = sqrt(col);\n"
"    col = min(vec3(1.0), col);\n"
"\n"
"    vec4 color = vec4(col, 1.0);\n"
"\n"
"    // imageStore(out0, pixel_coords, color);\n"
"    FragColor = color;\n"
"}\n"
"";
}
